USE [master]
GO

/****** Object:  Database [DB_NimapInfotech]    Script Date: 11/17/2024 5:03:31 PM ******/
CREATE DATABASE [DB_NimapInfotech]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_NimapInfotech', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DB_NimapInfotech.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DB_NimapInfotech_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DB_NimapInfotech_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_NimapInfotech].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_NimapInfotech] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_NimapInfotech] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_NimapInfotech] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_NimapInfotech] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_NimapInfotech] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_NimapInfotech] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DB_NimapInfotech] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_NimapInfotech] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_NimapInfotech] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_NimapInfotech] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_NimapInfotech] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_NimapInfotech] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_NimapInfotech] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_NimapInfotech] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_NimapInfotech] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DB_NimapInfotech] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_NimapInfotech] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB_NimapInfotech] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB_NimapInfotech] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_NimapInfotech] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_NimapInfotech] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DB_NimapInfotech] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB_NimapInfotech] SET RECOVERY FULL 
GO

ALTER DATABASE [DB_NimapInfotech] SET  MULTI_USER 
GO

ALTER DATABASE [DB_NimapInfotech] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB_NimapInfotech] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DB_NimapInfotech] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DB_NimapInfotech] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DB_NimapInfotech] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DB_NimapInfotech] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DB_NimapInfotech] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DB_NimapInfotech] SET  READ_WRITE 
GO

